name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.rst'
      - 'docs/**'
  push:
    branches:
      - main
      - cibuildwheel
    paths-ignore:
      - '**.rst'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build_test:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-11"]
        python: ["cp38", "cp39", "cp310", "cp311", "pp38", "pp39"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        make requirements
    - name: Build packages
      run: |
        python -m pip install cibuildwheel==2.12.3
        make c_lib
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64 universal2
        CIBW_BUILD: "${{ matrix.python }}-*"
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: ada-url-packages
        path: wheelhouse/*
