name: Build and test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.rst'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.rst'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build_test:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-11"]
        python: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        make requirements
    - name: Build packages for Linux
      if: "matrix.os == 'ubuntu-20.04'"
      run: |
        make package
    - name: Repair wheels for Linux
      if: "matrix.os == 'ubuntu-20.04'"
      run: |
        pip install -U auditwheel patchelf
    - name: Build packages for macOS
      if: "matrix.os == 'macos-11'"
      run: |
        make package
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9
    - name: Repair wheels for macOS
      if: "matrix.os == 'macos-11'"
      run: |
        pip install -U delocate
        delocate-wheel dist/ada_url-*macos*.whl
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.9
    - name: Run tests
      run: |
        pip install -e .
        make coverage
    - name: Build docs with sphinx
      if: "matrix.python == '3.8' && matrix.os == 'ubuntu-20.04'"
      run: |
        make docs
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: ada-url-packages
        path: dist/*
